server:
  port: 8080
  
spring:
  data:
    mongodb:
      database: supC2
      host: localhost
      port: 27017

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
      
upload:
  path: /home/ubuntu/PROJ/data
      